# Generated by Django 5.0.7 on 2026-04-04 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
